// Mocks generated by Mockito 5.4.4 from annotations
// in ragebait/test/features/paywall/paywall_sheet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:purchases_flutter/purchases_flutter.dart' as _i2;
import 'package:ragebait/core/services/api_service.dart' as _i5;
import 'package:ragebait/core/services/paywall_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCustomerInfo_0 extends _i1.SmartFake implements _i2.CustomerInfo {
  _FakeCustomerInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStoreProduct_1 extends _i1.SmartFake implements _i2.StoreProduct {
  _FakeStoreProduct_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePresentedOfferingContext_2 extends _i1.SmartFake
    implements _i2.PresentedOfferingContext {
  _FakePresentedOfferingContext_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$PackageCopyWith_3<$Res> extends _i1.SmartFake
    implements _i2.$PackageCopyWith<$Res> {
  _Fake$PackageCopyWith_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$StoreProductCopyWith_4<$Res> extends _i1.SmartFake
    implements _i2.$StoreProductCopyWith<$Res> {
  _Fake$StoreProductCopyWith_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PaywallService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaywallService extends _i1.Mock implements _i3.PaywallService {
  MockPaywallService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.CustomerInfo> getCustomerInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCustomerInfo,
          [],
        ),
        returnValue: _i4.Future<_i2.CustomerInfo>.value(_FakeCustomerInfo_0(
          this,
          Invocation.method(
            #getCustomerInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.CustomerInfo>);

  @override
  _i4.Future<bool> isUserPremium() => (super.noSuchMethod(
        Invocation.method(
          #isUserPremium,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> purchasePackage(_i2.Package? package) => (super.noSuchMethod(
        Invocation.method(
          #purchasePackage,
          [package],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> restorePurchases() => (super.noSuchMethod(
        Invocation.method(
          #restorePurchases,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.Package>> getCurrentOfferings() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentOfferings,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Package>>.value(<_i2.Package>[]),
      ) as _i4.Future<List<_i2.Package>>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> generateRagebait(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #generateRagebait,
          [topic],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #generateRagebait,
            [topic],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> syncPremiumStatus() => (super.noSuchMethod(
        Invocation.method(
          #syncPremiumStatus,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [Package].
///
/// See the documentation for Mockito's code generation for more information.
class MockPackage extends _i1.Mock implements _i2.Package {
  MockPackage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier => (super.noSuchMethod(
        Invocation.getter(#identifier),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#identifier),
        ),
      ) as String);

  @override
  _i2.PackageType get packageType => (super.noSuchMethod(
        Invocation.getter(#packageType),
        returnValue: _i2.PackageType.unknown,
      ) as _i2.PackageType);

  @override
  _i2.StoreProduct get storeProduct => (super.noSuchMethod(
        Invocation.getter(#storeProduct),
        returnValue: _FakeStoreProduct_1(
          this,
          Invocation.getter(#storeProduct),
        ),
      ) as _i2.StoreProduct);

  @override
  _i2.PresentedOfferingContext get presentedOfferingContext =>
      (super.noSuchMethod(
        Invocation.getter(#presentedOfferingContext),
        returnValue: _FakePresentedOfferingContext_2(
          this,
          Invocation.getter(#presentedOfferingContext),
        ),
      ) as _i2.PresentedOfferingContext);

  @override
  _i2.$PackageCopyWith<_i2.Package> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$PackageCopyWith_3<_i2.Package>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i2.$PackageCopyWith<_i2.Package>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [StoreProduct].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreProduct extends _i1.Mock implements _i2.StoreProduct {
  MockStoreProduct() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier => (super.noSuchMethod(
        Invocation.getter(#identifier),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#identifier),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);

  @override
  double get price => (super.noSuchMethod(
        Invocation.getter(#price),
        returnValue: 0.0,
      ) as double);

  @override
  String get priceString => (super.noSuchMethod(
        Invocation.getter(#priceString),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#priceString),
        ),
      ) as String);

  @override
  String get currencyCode => (super.noSuchMethod(
        Invocation.getter(#currencyCode),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#currencyCode),
        ),
      ) as String);

  @override
  _i2.$StoreProductCopyWith<_i2.StoreProduct> get copyWith =>
      (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$StoreProductCopyWith_4<_i2.StoreProduct>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i2.$StoreProductCopyWith<_i2.StoreProduct>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
